<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>To do List</title>

    <link rel="stylesheet" href="../styles/style.css">

</head>
<body>
    
    <nav>    
        <ul>
            <li><a href="home">Nueva nota</a></li>
            <li><a href="inicioSesion"><img width="32" height="32" src="https://img.icons8.com/windows/32/user-lock--v1.png" alt="user-lock--v1"/></a></li>
        </ul>
    </nav>