<?php require('header.phtml'); ?>

<div class="contenedor-general-tarea">
    <div class="contenedor-zona-titulo">
    <h1>to do list</h1>
    <?php if (isset($_SESSION['USER_ID'])) {?>
    <p>hola <?= $_SESSION['USER_NAME'] ?></p>
    <?php } else { ?>
    <p>hola</p>
    <?php } ?>
    </div>
    <div class="contenedor-agregar-tarea">
    <!-- agregar tareas -->
    <form action="agregarTarea" method="POST">
        <label for="">Tarea</label>
        <input type="text" name="nombreTarea">
        <label for="">Descripcion</label>
        <input type="text" name="descripcionTarea">
        <input type="submit" value="Agregar tarea">
    </form>
    </div>

    <div class="contenedor-tareas">
    <!-- tareas nuevas -->
    
    <?php foreach ($tareas as $tarea) :  ?>
        <div class="tarea">
        <b><?= $tarea->nombre_tarea?></b><br>
        <p><?= $tarea->contenido_tarea ?></p><a href="delete/<?= $tarea->id_tarea ?>">borrar</a><br>
        </div>
    <?php endforeach; ?>
  

    <div class="contendor-tareas-realizadas">
    <!-- tareas ya terminadas -->

    </div>
</div>

</body>
</html>
