<?php require('header.phtml'); ?>

<div class="contenedor-general-login">

    <div class="contenedor-zona-titulo">
        <h1>to do list</h1>
    </div>

    <div class="contenedor-login">
    <form action="sesionIniciada" method="POST">
        <label for="">nombre de usuario</label>
        <input type="text" name="nombre" id="">
        <label for="">contraseña</label>
        <input type="password" name="password">
        <input class="input-enviar" type="submit" value="Enviar">
        <a href="registro">no estoy registrado!</a>
    </form>
    </div>

</div>

<div class="contenedor-errores">
        <div class="mensaje">
                <p><?= $error ?></p> 
        </div>
</div>

</body>
</html>