<?php require('header.phtml'); ?>

<h1>to do list</h1>

<p>login</p>

<div class="contenedor-general-login">
    <form action="sesionIniciada" method="POST">
        <label for="">nombre</label>
        <input type="text" name="nombre" id="">
        <label for="">contraseña</label>
        <input type="password" name="password">
        <input type="submit" value="Enviar">
    </form>
    <a href="registro">no estoy registrado!</a>
</div>

<div class="contenedor-errores">
    <p><?= $error ?></p>
</div>

</body>
</html>