<?php require('header.phtml'); ?>

<div class="contenedor-general-perfil">

    <div class="contenedor-zona-titulo">
        <h1>to do list</h1>
    </div>

    <div class="contenedor-opciones">
        <a href="sesionTerminada"><button>salir</button></a>
        <a href="borrarCuenta/<?= $_SESSION['USER_ID'] ?>"><button class="btn-borrar">Borrar cuenta</button></a>
    </div>
</div>

</body>
</html>