<?php require('header.phtml'); ?>

<h1>to do list</h1>

<p>registro</p>

<div class="contenedor-general-login">
    <form action="sesionIniciada">
        <label for="">nombre de usuario</label>
        <input type="text" name="" id="">
        <label for="">mail</label>
        <input type="email" name="" id="">
        <label for="">contraseña</label>
        <input type="password">
        <input type="submit">
        <a href="login">ya estoy registrado!</a>
    </form>
</div>

</body>
</html>