<?php require('header.phtml'); ?>

<div class="contenedor-general-login">

    <div class="contenedor-zona-titulo">
        <h1>to do list</h1>
    </div>

    <div class="contenedor-registro">
    <form action="sesionRegistrada" method="POST">
        <label for="">nombre de usuario</label>
        <input type="text" name="nombre" id="" required>
        <label for="">mail</label>
        <input type="email" name="mail" id="" required>
        <label for="">contraseña</label>
        <input type="password" name="password" required>
        <input class="input-enviar" type="submit" value="Enviar">
        <a href="login">ya estoy registrado!</a>
    </form>
    </div>
</div>

<div class="contenedor-errores">
    <p><?= $error ?></p>
</div>

</body>
</html>